create table customers(
Customer_ID int primary key,
Age int,
Gender varchar(10),
Item_Purchased varchar(50),
Category varchar(100),
Purchase_Amount int,
Location varchar(150),
Size varchar(4),
Color varchar(100),
Season varchar(50),
Review_Rating float,
Subscription_Status varchar(10),
Shipping_Type varchar(100),
Discount_Applied varchar(10),
Promo_Code_Used varchar(4),
Previous_Purchases int,
Payment_Method varchar(100),
Frequency_of_Purchases varchar(100)
);

select * from customers;
--Q1. What is the total revenue generated by male vs. female customers?
  select gender, sum(purchase_amount) as total_revenue
  from customers
  group by gender;

----Q2. Which customers used a discount but still spent more than the average purchase amount? 
    select customer_id ,purchase_amount
	from customers
	where discount_applied = 'Yes' and purchase_amount>=(
	select avg(purchase_amount) from customers);

---- Q3. Which are the top 5 products with the highest average review rating?
 	select item_purchased, round(avg(purchase_amount),2) as avg_total
	 from customers 
	 group by item_purchased
	 order by avg(purchase_amount) desc
	 limit 5;
	 
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
     select shipping_type, round(avg(purchase_amount),2) as avg_amount
	 from customers
	where shipping_type in ('Standard', 'Express')
	group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

 select subscription_status,
     count(*) as number_of_sub,
	 round(avg(purchase_amount),2) as avg_total,
	 sum(purchase_amount) as total_revenue
	 from customers
	 group by subscription_status
	 order by avg_total, total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
   select  item_purchased, 
          ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
          FROM customers
            group by item_purchased
		     order by discount_rate desc;

--Q8. What are the top 3 most purchased products within each category? 
 with cte as
 (select
         dense_rank() over(partition by category order by count(customer_id) desc )as rnk, category, 
         item_purchased,
          count(customer_id) as total_orders
            from customers
     group by category , item_purchased) 
     select rnk , category, item_purchased,total_orders from cte where rnk <=3; 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
  select subscription_status,
  count(customer_id) as repeat_busyer
  from customers
  where previous_purchases>5
  group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
  select age,
        sum(purchase_amount) as revenue
		from customers
		group by age
		order by revenue desc;


  

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS Number_of_customer 
from cte 
group by customer_segment
order by Number_of_customer;


 